/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JPanelPath.java
 *
 * Created on 16 nov. 2010, 19:54:53
 */

package gp.utils.swing.filechooser.path;

/**
 *
 * @author gpasquiers
 */
public class PathView extends javax.swing.JPanel {

    /** Creates new form JPanelPath */
    public PathView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonLeft = new javax.swing.JButton();
        jButtonRight = new javax.swing.JButton();
        jPanelButtons = new javax.swing.JPanel();

        jButtonLeft.setText("<");
        jButtonLeft.setEnabled(false);
        jButtonLeft.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonLeft.setName("jButtonLeft"); // NOI18N

        jButtonRight.setText(">");
        jButtonRight.setEnabled(false);
        jButtonRight.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButtonRight.setName("jButtonRight"); // NOI18N

        jPanelButtons.setName("jPanelButtons"); // NOI18N
        jPanelButtons.setLayout(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButtonLeft)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelButtons, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRight))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelButtons, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
            .addComponent(jButtonLeft, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonRight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton jButtonLeft;
    protected javax.swing.JButton jButtonRight;
    protected javax.swing.JPanel jPanelButtons;
    // End of variables declaration//GEN-END:variables

}
