/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JPanelPlacesCellRenderer.java
 *
 * Created on 9 nov. 2010, 22:25:28
 */

package gp.utils.swing.filechooser.common;

/**
 *
 * @author gpasquiers
 */
public class FileCellRendererSeparatorView extends javax.swing.JPanel {

    /** Creates new form JPanelPlacesCellRenderer */
    public FileCellRendererSeparatorView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();

        setBackground(javax.swing.UIManager.getDefaults().getColor("Table.background"));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jSeparator1.setName("jSeparator1"); // NOI18N
        add(jSeparator1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
