/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JPanelFiles.java
 *
 * Created on 21 nov. 2010, 14:15:00
 */

package gp.utils.swing.filechooser.files;

/**
 *
 * @author gpasquiers
 */
public class FilesView extends javax.swing.JPanel {

    /** Creates new form JPanelFiles */
    public FilesView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPopupMenuFiles = new javax.swing.JPopupMenu();
        jPopupMenuFiles_HiddenFilesItem = new javax.swing.JCheckBoxMenuItem();
        jComboBoxCustomFilters = new javax.swing.JComboBox();
        jScrollPaneFiles = new javax.swing.JScrollPane();
        jTableFiles = new javax.swing.JTable();
        jTextFieldFilter = new javax.swing.JTextField();

        jPopupMenuFiles_HiddenFilesItem.setText("Show Hidden Files");
        jPopupMenuFiles.add(jPopupMenuFiles_HiddenFilesItem);

        setLayout(new java.awt.GridBagLayout());

        jComboBoxCustomFilters.setMinimumSize(new java.awt.Dimension(204, 21));
        jComboBoxCustomFilters.setPreferredSize(new java.awt.Dimension(204, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        add(jComboBoxCustomFilters, gridBagConstraints);

        jTableFiles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Size", "Last modified"
            }
        ));
        jTableFiles.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        jTableFiles.setIntercellSpacing(new java.awt.Dimension(0, 1));
        jTableFiles.setShowHorizontalLines(false);
        jTableFiles.setShowVerticalLines(false);
        jScrollPaneFiles.setViewportView(jTableFiles);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jScrollPaneFiles, gridBagConstraints);

        jTextFieldFilter.setMaximumSize(new java.awt.Dimension(204, 21));
        jTextFieldFilter.setMinimumSize(new java.awt.Dimension(204, 21));
        jTextFieldFilter.setPreferredSize(new java.awt.Dimension(204, 21));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        add(jTextFieldFilter, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JComboBox jComboBoxCustomFilters;
    protected javax.swing.JPopupMenu jPopupMenuFiles;
    protected javax.swing.JCheckBoxMenuItem jPopupMenuFiles_HiddenFilesItem;
    protected javax.swing.JScrollPane jScrollPaneFiles;
    protected javax.swing.JTable jTableFiles;
    protected javax.swing.JTextField jTextFieldFilter;
    // End of variables declaration//GEN-END:variables

}
