/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * jPanelPlaces.java
 *
 * Created on 21 nov. 2010, 16:01:12
 */

package gp.utils.swing.filechooser.places;

/**
 *
 * @author gpasquiers
 */
public class PlacesView extends javax.swing.JPanel {

    /** Creates new form jPanelPlaces */
    public PlacesView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelPlaces_jButtonAdd = new javax.swing.JButton();
        jPanelPlaces_jButtonRemove = new javax.swing.JButton();
        jPanelPlaces_jScrollBar = new javax.swing.JScrollPane();
        jPanelPlaces_jTablePlaces = new javax.swing.JTable();

        jPanelPlaces_jButtonAdd.setText("Add");
        jPanelPlaces_jButtonAdd.setEnabled(false);

        jPanelPlaces_jButtonRemove.setText("Remove");
        jPanelPlaces_jButtonRemove.setEnabled(false);

        setLayout(new java.awt.GridBagLayout());

        jPanelPlaces_jScrollBar.setBackground(javax.swing.UIManager.getDefaults().getColor("Table.background"));
        jPanelPlaces_jScrollBar.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jPanelPlaces_jScrollBar.setPreferredSize(new java.awt.Dimension(452, 200));

        jPanelPlaces_jTablePlaces.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Places"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jPanelPlaces_jTablePlaces.setIntercellSpacing(new java.awt.Dimension(0, 0));
        jPanelPlaces_jTablePlaces.setShowHorizontalLines(false);
        jPanelPlaces_jTablePlaces.setShowVerticalLines(false);
        jPanelPlaces_jScrollBar.setViewportView(jPanelPlaces_jTablePlaces);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jPanelPlaces_jScrollBar, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jPanelPlaces_jButtonAdd;
    private javax.swing.JButton jPanelPlaces_jButtonRemove;
    protected javax.swing.JScrollPane jPanelPlaces_jScrollBar;
    protected javax.swing.JTable jPanelPlaces_jTablePlaces;
    // End of variables declaration//GEN-END:variables

}
