/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JPanelPlacesCellRenderer.java
 *
 * Created on 9 nov. 2010, 22:25:28
 */

package gp.utils.swing.filechooser.common;

/**
 *
 * @author gpasquiers
 */
public class FileCellRendererFileView extends javax.swing.JPanel {

    /** Creates new form JPanelPlacesCellRenderer */
    public FileCellRendererFileView() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabelIcon = new javax.swing.JLabel();
        jLabelText = new javax.swing.JLabel();

        setBackground(javax.swing.UIManager.getDefaults().getColor("Table.background"));
        setLayout(new java.awt.GridBagLayout());

        jLabelIcon.setMaximumSize(new java.awt.Dimension(16, 16));
        jLabelIcon.setMinimumSize(new java.awt.Dimension(16, 16));
        jLabelIcon.setName("jLabelIcon"); // NOI18N
        jLabelIcon.setPreferredSize(new java.awt.Dimension(16, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 4);
        add(jLabelIcon, gridBagConstraints);

        jLabelText.setText("jLabel2");
        jLabelText.setMaximumSize(new java.awt.Dimension(34, 16));
        jLabelText.setMinimumSize(new java.awt.Dimension(34, 16));
        jLabelText.setName("jLabelText"); // NOI18N
        jLabelText.setPreferredSize(new java.awt.Dimension(34, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jLabelText, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JLabel jLabelIcon;
    protected javax.swing.JLabel jLabelText;
    // End of variables declaration//GEN-END:variables

}
